server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Основной роут для SPA
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Отключение кэширования для index.html, чтобы пользователи всегда получали свежую версию приложения
    location = /index.html {
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }

    # Кэширование статики на 30 дней
    location ~* \.(?:css|js|jpg|svg|ico)$ {
        expires 30d;
        add_header Cache-Control "public";
    }
}
